// this is for popular recipes 
export const popularRecipes = [
    { id: 1, name: "Popular🔥", },
    { id: 2, name: "African", },
    { id: 3, name: "Fresh", },
    { id: 4, name: "Hot sales🥧", },
    { id: 5, name: "Promotion", },
]

// this is for popular picks data
export const popularPicksData = [
    {
        "id": 1,
        "name": "Efo Riro & Pounded Yam",
        "price": "N4,000",
        "deliveryTime": "30mins",
        "image": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea",
        "category": "Nigerian Soup",
        "rating": 4.5,
        "description": "Traditional Nigerian vegetable soup with smooth pounded yam",
        "distance": "5 km",
        "overTime": "5 mins"
    },
    {
        "id": 2,
        "name": "Jollof Rice & Chicken",
        "price": "N3,500",
        "deliveryTime": "25mins",
        "image": "https://images.unsplash.com/photo-1598511759936-3c4c1c42b0bf",
        "category": "Rice Dish",
        "rating": 4.7,
        "description": "Spicy tomato rice with grilled chicken and plantain",
        "distance": "7 km",
        "overTime": "10 mins"
    },
    {
        "id": 3,
        "name": "Amala & Ewedu",
        "price": "N3,200",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8",
        "category": "Swallow",
        "rating": 4.3,
        "description": "Yam flour swallow with jute leaves soup",
        "distance": "3 km",
        "overTime": "7 mins"
    },
    {
        "id": 4,
        "name": "Ofada Rice & Ayamase",
        "price": "N4,500",
        "deliveryTime": "40mins",
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        "category": "Local Delicacy",
        "rating": 4.6,
        "description": "Local rice with special pepper sauce",
        "distance": "6 km",
        "overTime": "8 mins"
    },
    {
        "id": 5,
        "name": "Pepper Soup & Semo",
        "price": "N3,800",
        "deliveryTime": "30mins",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
        "category": "Soup",
        "rating": 4.4,
        "description": "Spicy assorted meat soup with semolina",
        "distance": "4 km",
        "overTime": "5 mins"
    },
    {
        "id": 6,
        "name": "Egusi Soup & Fufu",
        "price": "N3,600",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
        "category": "Soup",
        "rating": 4.5,
        "description": "Melon seed soup with cassava fufu",
        "distance": "8 km",
        "overTime": "10 mins"
    },
    {
        "id": 7,
        "name": "Fried Rice & Beef",
        "price": "N3,200",
        "deliveryTime": "25mins",
        "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19",
        "category": "Rice Dish",
        "rating": 4.2,
        "description": "Mixed vegetable fried rice with beef",
        "distance": "5 km",
        "overTime": "6 mins"
    },
    {
        "id": 8,
        "name": "Ogbono Soup & Wheat",
        "price": "N3,400",
        "deliveryTime": "30mins",
        "image": "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
        "category": "Soup",
        "rating": 4.3,
        "description": "African mango seed soup with wheat swallow",
        "distance": "7 km",
        "overTime": "9 mins"
    },
    {
        "id": 9,
        "name": "Moi Moi & Pap",
        "price": "N2,500",
        "deliveryTime": "20mins",
        "image": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327",
        "category": "Breakfast",
        "rating": 4.1,
        "description": "Steamed bean pudding with corn pap",
        "distance": "3 km",
        "overTime": "4 mins"
    },
    {
        "id": 10,
        "name": "Suya & Dambu Nama",
        "price": "N4,200",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
        "category": "Grilled Meat",
        "rating": 4.8,
        "description": "Spicy grilled beef with shredded meat",
        "distance": "6 km",
        "overTime": "7 mins"
    },
    {
        "id": 11,
        "name": "Banga Soup & Starch",
        "price": "N4,300",
        "deliveryTime": "45mins",
        "image": "https://images.unsplash.com/photo-1565299507177-b0ac66763828",
        "category": "Soup",
        "rating": 4.4,
        "description": "Palm fruit soup with cassava starch",
        "distance": "5 km",
        "overTime": "10 mins"
    },
    {
        "id": 12,
        "name": "White Rice & Stew",
        "price": "N2,800",
        "deliveryTime": "20mins",
        "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
        "category": "Rice Dish",
        "rating": 4.0,
        "description": "Plain rice with tomato stew",
        "distance": "4 km",
        "overTime": "3 mins"
    },
    {
        "id": 13,
        "name": "Afang Soup & Garri",
        "price": "N4,100",
        "deliveryTime": "40mins",
        "image": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8",
        "category": "Soup",
        "rating": 4.6,
        "description": "Vegetable soup with cassava flakes",
        "distance": "8 km",
        "overTime": "7 mins"
    },
    {
        "id": 14,
        "name": "Nkwobi & Isi Ewu",
        "price": "N4,800",
        "deliveryTime": "50mins",
        "image": "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
        "category": "Special Delicacy",
        "rating": 4.7,
        "description": "Spicy cow foot and goat head",
        "distance": "10 km",
        "overTime": "12 mins"
    },
    {
        "id": 15,
        "name": "Beans & Plantain",
        "price": "N2,200",
        "deliveryTime": "25mins",
        "image": "https://images.unsplash.com/photo-1563379926898-05f4575a45d8",
        "category": "Local Dish",
        "rating": 4.2,
        "description": "Honey beans with fried plantain",
        "distance": "5 km",
        "overTime": "6 mins"
    },
    {
        "id": 16,
        "name": "Okro Soup & Eba",
        "price": "N3,300",
        "deliveryTime": "30mins",
        "image": "https://images.unsplash.com/photo-1512058564366-18510be2db19",
        "category": "Soup",
        "rating": 4.3,
        "description": "Okra soup with garri swallow",
        "distance": "6 km",
        "overTime": "7 mins"
    },
    {
        "id": 17,
        "name": "Yam Porridge",
        "price": "N2,600",
        "deliveryTime": "25mins",
        "image": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327",
        "category": "Porridge",
        "rating": 4.1,
        "description": "Yam cooked in pepper sauce",
        "distance": "4 km",
        "overTime": "5 mins"
    },
    {
        "id": 18,
        "name": "Catfish Pepper Soup",
        "price": "N3,900",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
        "category": "Soup",
        "rating": 4.5,
        "description": "Spicy catfish soup with vegetables",
        "distance": "7 km",
        "overTime": "10 mins"
    },
    {
        "id": 19,
        "name": "Pounded Yam & Egusi",
        "price": "N3,700",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea",
        "category": "Soup",
        "rating": 4.4,
        "description": "Pounded yam with melon seed soup",
        "distance": "5 km",
        "overTime": "8 mins"
    },
    {
        "id": 20,
        "name": "Fried Plantain & Egg",
        "price": "N2,000",
        "deliveryTime": "15mins",
        "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
        "category": "Breakfast",
        "rating": 4.0,
        "description": "Fried ripe plantain with scrambled eggs",
        "distance": "3 km",
        "overTime": "4 mins"
    },
    {
        "id": 21,
        "name": "Ewa Agoyin & Bread",
        "price": "N1,800",
        "deliveryTime": "20mins",
        "image": "https://images.unsplash.com/photo-1565299507177-b0ac66763828",
        "category": "Local Dish",
        "rating": 4.2,
        "description": "Mashed beans with special sauce and bread",
        "distance": "6 km",
        "overTime": "5 mins"
    },
    {
        "id": 22,
        "name": "Fisherman Soup & Semo",
        "price": "N4,500",
        "deliveryTime": "45mins",
        "image": "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
        "category": "Seafood",
        "rating": 4.6,
        "description": "Seafood soup with semolina",
        "distance": "8 km",
        "overTime": "10 mins"
    },
    {
        "id": 23,
        "name": "Asaro & Fish",
        "price": "N3,100",
        "deliveryTime": "30mins",
        "image": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327",
        "category": "Porridge",
        "rating": 4.3,
        "description": "Yam porridge with fish",
        "distance": "5 km",
        "overTime": "6 mins"
    },
    {
        "id": 24,
        "name": "Goat Meat Pepper Soup",
        "price": "N3,600",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b",
        "category": "Soup",
        "rating": 4.4,
        "description": "Spicy goat meat soup",
        "distance": "7 km",
        "overTime": "8 mins"
    },
    {
        "id": 25,
        "name": "Akpu & Oha Soup",
        "price": "N3,800",
        "deliveryTime": "40mins",
        "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
        "category": "Soup",
        "rating": 4.5,
        "description": "Cassava fufu with oha leaves soup",
        "distance": "6 km",
        "overTime": "9 mins"
    },
    {
        "id": 26,
        "name": "Rice & Beans",
        "price": "N2,400",
        "deliveryTime": "20mins",
        "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
        "category": "Rice Dish",
        "rating": 4.1,
        "description": "Mixed rice and beans",
        "distance": "3 km",
        "overTime": "5 mins"
    },
    {
        "id": 27,
        "name": "Tuwon Masara & Miyan Kuka",
        "price": "N3,200",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
        "category": "Northern Dish",
        "rating": 4.3,
        "description": "Corn swallow with baobab leaves soup",
        "distance": "9 km",
        "overTime": "11 mins"
    },
    {
        "id": 28,
        "name": "Edikaikong & Pounded Yam",
        "price": "N4,200",
        "deliveryTime": "40mins",
        "image": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea",
        "category": "Soup",
        "rating": 4.7,
        "description": "Vegetable soup with pounded yam",
        "distance": "6 km",
        "overTime": "8 mins"
    },
    {
        "id": 29,
        "name": "White Soup & Fufu",
        "price": "N3,900",
        "deliveryTime": "35mins",
        "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
        "category": "Soup",
        "rating": 4.4,
        "description": "Ofe nsala with cassava fufu",
        "distance": "4 km",
        "overTime": "7 mins"
    },
    {
        "id": 30,
        "name": "Abacha & Ugba",
        "price": "N2,700",
        "deliveryTime": "25mins",
        "image": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327",
        "category": "Salad",
        "rating": 4.2,
        "description": "African salad with palm fruit",
        "distance": "5 km",
        "overTime": "6 mins"
    }
]

